### ISSUE TITLE
cannot access original game launcher (Skyrim SE)

### ISSUE THREAD

**Issue by accidentalcoincidence** [ralgar/proton-mo2-installer#11]
the readme page mentions changing the path for the game launcher to a backup of the original executable, however this backup does not exist in my game folder and was apparently not created during installation

(i'm going to work around this by editing the .ini file directly)

**Comment by ralgar** [comment]
Looks like this was a bug in the uninstall function, which you ran into because of the initial installation failure. I've fixed the tracking of instance state, so this shouldn't happen in future.

If you want to get your Launcher executable back, here's what I suggest:

1. Download latest release of proton-mo2-installer (v1.0.4).
2. Run the proton-mo2-installer "Uninstall" function.
3. Verify your game's files in Steam.
4. Run the proton-mo2-installer "Install" function.

Doing this shouldn't affect your MO2 instance in any way (always backup to be safe though), but you may need to reinstall any mods which you've installed manually to the game's directory, such as SSE Engine Fixes Part 2.

**Comment by accidentalcoincidence** [comment]
i managed to make all necessary changes in the files directly, but thank you nonetheless!
