### ISSUE TITLE
Fallout 4 Script Extender Downloads Wrong

### ISSUE THREAD

**Issue by cprin21** [ralgar/proton-mo2-installer#5]
When installing proton-mo2-installer for Fallout 4, F4SE installs to a folder within the game's base directory instead of installing normally to work out of the box like how it is in Skyrim Special Edition, Oblivion, and New Vegas (non Russian edition).

**Comment by ralgar** [comment]
Thanks for the info. I don't own FO4, but I'll see what I can do when I get a minute.

I wanted to ask. Have you noticed a lot of CTDs with Skyrim? I finally updated my mod stack for 1.6.xxx and it seems like the bundled version of Proton causes CTDs in game. If you're having this problem you can switch to Proton 7.0-3 when playing, it seems to be stable.

MO2 really needs to be fixed in official Proton. I'm going to submit an issue to Valve when I have a minute.

**Comment by cprin21** [comment]
I hadn't noticed crashing problems with Skyrim SE - but what I have noticed is abysmal performance.
It seems like there is a lot of incompatible engine stuff that seems to prefer Windows greatly. Getting drops down to mid 40s in Solitude and so on which is disturbing to see on a 2070S when I had it installed.

**Comment by cprin21** [comment]
Also, Fallout 4 Script Extender isn't downloading wrong, really. It downloads just fine. The archive file is formatted to have a folder that the script extender files are inside which is the folder that ends up in the Fallout 4 base directory. Modifying the script in some way where it would take the files and folders *within* that folder to place in the base directory is probably the fix for this issue.

**Comment by ralgar** [comment]
This should work as of [v1.0.1](https://github.com/ralgar/proton-mo2-installer/releases/tag/v1.0.1). The code for stripping that leading directory was already written, I just had to fix the configuration for F4SE. I also updated F4SE to the latest version.

Let me know if it doesn't work.
